apiVersion: v1        # Specifies the API version of the Kubernetes Service API
kind: Service         # Specifies the type of Kubernetes resource to create, in this case, a Service
metadata:             # Contains metadata for the Service resource
  name: springboot-mongo-app-service  # Specifies the name of the Service resource
spec:                 # Specifies the Service's specification
  type: LoadBalancer  # Specifies the type of Service to create. 'LoadBalancer' exposes the Service externally using a cloud provider's load balancer
  selector:           # Specifies the label selector to identify which Pods belong to this Service
    app: springboot-mongo-app   # A label with key 'app' and value 'springboot-mongo-app'
  ports:              # Specifies the ports to be exposed by the Service
    - port: 8090     # Specifies the port number for the Service
      targetPort: 8080  # Specifies the port number on the Pods that the Service should forward traffic to
